id: P44E69003
initial_creation_type: ocr
source_metadata:
  volumes:
    f9dec807671f45ce9de1dda1afbd0553:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: རྨི་ལམ་ཡིད་བཞིན་ནོར་བུའི་གཏམ།
      total_pages: 1144
      volume_number: 96
